# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lloyd Helen Architecture & Design
email: lloydhelen123@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This website is still being developed. Please visit ISSUU to view my portfolio while I finish things up. Thanks.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lloydhelen.com" # the base hostname & protocol for your site
twitter_username: lloydhelen123
github_username:  lloydhelen123

# Build settings
markdown: kramdown
